[package]
name = "envify"
version = "0.1.0"
authors = ["Damien Castelltort <dcastelltort@gmail.com>"]

[dependencies]
serde = "1.0.55"                      # A generic serialization/deserialization framework
serde_json = "1.0.17"                 # A JSON serialization file format
quicli = "0.2"